[package]
name = "yaso"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
rquickjs = { version = "0.5", features = ["bindgen", "full", "rust-alloc"] }
